# Generated by Django 3.0.8 on 2020-07-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200716_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='category_id',
        ),
    ]
