# Generated by Django 3.0.8 on 2020-07-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200716_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50),
        ),
    ]
