# Generated by Django 3.0.8 on 2020-07-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200717_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(db_constraint=None, on_delete=django.db.models.deletion.CASCADE, to='job.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=50),
        ),
    ]
